
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD BACKUP CONFIGURE COPY CREATE DELETE EXEC ID MODIFY PATH RENAME STRING TRANSFERcommand : configureconfigure : CONFIGURE paramsparams : params paramparams : paramparam : "-" ID "-" ">" argumentargument : ID\n              | STRING\n              | PATH'
    
_lr_action_items = {'CONFIGURE':([0,],[3,]),'$end':([1,2,4,5,7,11,12,13,14,],[0,-1,-2,-4,-3,-6,-5,-7,-8,]),'-':([3,4,5,7,8,11,12,13,14,],[6,6,-4,-3,9,-6,-5,-7,-8,]),'ID':([6,10,],[8,11,]),'>':([9,],[10,]),'STRING':([10,],[13,]),'PATH':([10,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'configure':([0,],[2,]),'params':([3,],[4,]),'param':([3,4,],[5,7,]),'argument':([10,],[12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> configure','command',1,'p_command','parser.py',45),
  ('configure -> CONFIGURE params','configure',2,'p_configure','parser.py',49),
  ('params -> params param','params',2,'p_params','parser.py',53),
  ('params -> param','params',1,'p_simgle_param','parser.py',57),
  ('param -> - ID - > argument','param',5,'p_param','parser.py',61),
  ('argument -> ID','argument',1,'p_argument','parser.py',65),
  ('argument -> STRING','argument',1,'p_argument','parser.py',66),
  ('argument -> PATH','argument',1,'p_argument','parser.py',67),
]
